# Generated by Django 4.2.11 on 2024-05-14 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soul', '0003_recipe_image_alter_recipe_instructions_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='recipe',
            name='likes',
        ),
    ]
